import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static const supportedLocales = [Locale('fr'), Locale('en')];

  static AppLocalizations of(BuildContext context) {
    final AppLocalizations? instance = Localizations.of<AppLocalizations>(context, AppLocalizations);
    assert(instance != null, 'No AppLocalizations found in context');
    return instance!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  static const Map<String, Map<String, String>> _localizedValues = {
    'fr': {
      'appTitle': 'EduGest',
      'welcomeTitle': 'Bienvenue sur EduGest',
      'welcomeDescription': 'Une application pour gérer vos données scolaires facilement.',
      'getStarted': 'Commencer',
      'loginTitle': 'Se connecter',
      'loginSubtitle': 'Accédez à votre espace de gestion scolaire.',
      'chooseRole': 'CHOISISSEZ VOTRE RÔLE',
      'connectButton': 'Se connecter',
      'settingsTitle': 'Paramètres de l\'application',
      'preferences': 'Préférences',
      'fullName': 'Nom complet',
      'emailAddress': 'Adresse e-mail',
      'nameRequired': 'Veuillez renseigner votre nom',
      'emailRequired': 'Veuillez renseigner votre e-mail',
      'notificationsActive': 'Notifications actives',
      'applicationLanguage': 'Langue de l\'application',
      'savePreferences': 'Sauvegarder les préférences',
      'preferencesSaved': 'Préférences sauvegardées avec succès.',
      'support': 'Support',
      'helpCenter': 'Centre d\'aide',
      'privacyPolicy': 'Politique de confidentialité',
      'languageFrench': 'Français',
      'languageEnglish': 'Anglais',
      'emailHint': 'Adresse email',
      'passwordHint': 'Mot de passe',
      'principal': 'Principal',
      'schoolLife': 'Vie Scolaire',
      'administration': 'Administration',
      'dashboard': 'Tableau de bord',
      'timetable': 'Emploi du temps',
      'students': 'Élèves',
      'teachers': 'Enseignants',
      'myNotes': 'Mes Notes',
      'myNotebook': 'Mon Cahier de Texte',
      'adminAnnouncements': 'Annonces Admin',
      'receptionNotes': 'Réception Notes',
      'receptionNotebooks': 'Réception Cahiers',
      'events': 'Événements',
      'discipline': 'Discipline',
      'managementStaff': 'Gestion Staff',
      'payments': 'Paiements',
      'expenses': 'Dépenses',
      'classes': 'Classes',
      'subjects': 'Matières',
      'settings': 'Paramètres',
      'profile': 'Profil',
      'overviewWelcome': 'Bienvenue dans votre espace EduGest',
      'overviewSelectMenu': 'Sélectionnez un menu à gauche pour commencer',
      'dashboardTitle': 'Pilotage Établissement',
      'staffActivity': 'Activités récentes du staff',
      'effectif': 'Effectif',
      'successRate': 'Réussite',
      'revenue': 'Recettes',
      'planningEvents': 'Planning & Événements',
      'add': 'Ajouter',
      'newEvent': 'Nouvel Événement',
      'title': 'Titre',
      'category': 'Catégorie',
      'dateLabel': 'Date',
      'timeLabel': 'Heure',
      'cancel': 'Annuler',
      'searchPlaceholder': 'Rechercher...',
      'noEvents': 'Aucun événement',
      'all': 'Tous',
      'council': 'Conseil',
      'exam': 'Examen',
      'meeting': 'Réunion',
      'ceremony': 'Cérémonie',
      'absenceTracking': 'Suivi des Absences',
      'report': 'Signaler',
      'today': 'Aujourd\'hui',
      'thisWeek': 'Cette semaine',
      'thisMonth': 'Ce mois',
      'studentName': 'Élève Nom',
      'classLabel': 'Classe',
      'justified': 'Justifiée',
      'lessonBook': 'Cahier de Texte',
      'lessonEditing': 'Modification de la Leçon',
      'entryTab': 'Saisie',
      'myPosts': 'Mes Publications',
      'editingMode': 'Mode Modification',
      'classConcerned': 'Classe concernée',
      'detailedContent': 'Contenu détaillé',
      'lessonTitleHint': 'Titre de la leçon',
      'lessonDetailHint': 'Détaillez le cours ici...',
      'publishLesson': 'Publier la leçon',
      'updateLesson': 'Mettre à jour',
      'lessonSavedSuccess': 'Leçon enregistrée avec succès !',
      'notesManagement': 'Gestion des Notes',
      'notesEdition': 'Modification des Notes',
      'mySubmissions': 'Mes Envois',
      'sendToAdmin': 'Envoyer à l\'administration',
      'updateSubmission': 'Mettre à jour l\'envoi',
      'modificationModeActive': 'Mode Modification activé',
      'studentsNotFound': 'Aucun élève trouvé.',
      'operationSuccess': 'Opération réussie !',
      'dashboardComptable': 'Tableau de bord Comptable',
      'dashboardEnseignant': 'Tableau de bord Enseignant',
      'dashboardFondateur': 'Tableau de bord Fondateur',
      'dashboardSecretaire': 'Tableau de bord Secrétaire',
      'dashboardSurveillantGeneral': 'Tableau de bord Surveillant Général',
      'dashboardProviseur': 'Tableau de bord Proviseur',
      'activityUpdatedSchedule': 'Emploi du temps mis à jour',
      'activityBulletinValidated': 'Bulletin validé',
      'activityAbsencesToProcess': 'Absences à traiter',
      'logout': 'Déconnexion',
      'appel': 'Faire l\'appel',
      'recapYears': 'Récapitulatif Années',
      'bulletins': 'Bulletins Scolaires',
    },
    'en': {
      'appTitle': 'EduGest',
      'welcomeTitle': 'Welcome to EduGest',
      'welcomeDescription': 'An app for managing your school data with ease.',
      'getStarted': 'Get Started',
      'loginTitle': 'Sign In',
      'loginSubtitle': 'Access your school management dashboard.',
      'chooseRole': 'CHOOSE YOUR ROLE',
      'connectButton': 'Sign In',
      'settingsTitle': 'Application Settings',
      'preferences': 'Preferences',
      'fullName': 'Full Name',
      'emailAddress': 'Email Address',
      'nameRequired': 'Please enter your name',
      'emailRequired': 'Please enter your email',
      'notificationsActive': 'Active Notifications',
      'applicationLanguage': 'Application Language',
      'savePreferences': 'Save Preferences',
      'preferencesSaved': 'Preferences saved successfully.',
      'support': 'Support',
      'helpCenter': 'Help Center',
      'privacyPolicy': 'Privacy Policy',
      'languageFrench': 'French',
      'languageEnglish': 'English',
      'emailHint': 'Email address',
      'passwordHint': 'Password',
      'principal': 'Main',
      'schoolLife': 'School Life',
      'administration': 'Administration',
      'dashboard': 'Dashboard',
      'timetable': 'Timetable',
      'students': 'Students',
      'teachers': 'Teachers',
      'myNotes': 'My Notes',
      'myNotebook': 'My Notebook',
      'adminAnnouncements': 'Admin Announcements',
      'receptionNotes': 'Notes Reception',
      'receptionNotebooks': 'Notebook Reception',
      'events': 'Events',
      'discipline': 'Discipline',
      'managementStaff': 'Staff Management',
      'payments': 'Payments',
      'expenses': 'Expenses',
      'classes': 'Classes',
      'subjects': 'Subjects',
      'settings': 'Settings',
      'profile': 'Profile',
      'overviewWelcome': 'Welcome to your EduGest workspace',
      'overviewSelectMenu': 'Select a menu on the left to begin',
      'dashboardTitle': 'School Management',
      'staffActivity': 'Recent staff activity',
      'effectif': 'Student body',
      'successRate': 'Success rate',
      'revenue': 'Revenue',
      'planningEvents': 'Planning & Events',
      'add': 'Add',
      'newEvent': 'New Event',
      'title': 'Title',
      'category': 'Category',
      'dateLabel': 'Date',
      'timeLabel': 'Time',
      'cancel': 'Cancel',
      'searchPlaceholder': 'Search...',
      'noEvents': 'No events',
      'all': 'All',
      'council': 'Council',
      'exam': 'Exam',
      'meeting': 'Meeting',
      'ceremony': 'Ceremony',
      'absenceTracking': 'Absence Tracking',
      'report': 'Report',
      'today': 'Today',
      'thisWeek': 'This week',
      'thisMonth': 'This month',
      'studentName': 'Student Name',
      'classLabel': 'Class',
      'justified': 'Justified',
      'lessonBook': 'Lesson Notebook',
      'lessonEditing': 'Lesson Editing',
      'entryTab': 'Entry',
      'myPosts': 'My Posts',
      'editingMode': 'Edit Mode',
      'classConcerned': 'Class',
      'detailedContent': 'Detailed content',
      'lessonTitleHint': 'Lesson title',
      'lessonDetailHint': 'Describe the lesson here...',
      'publishLesson': 'Publish lesson',
      'updateLesson': 'Update',
      'lessonSavedSuccess': 'Lesson saved successfully!',
      'notesManagement': 'Notes Management',
      'notesEdition': 'Notes Editing',
      'mySubmissions': 'My Submissions',
      'sendToAdmin': 'Send to administration',
      'updateSubmission': 'Update submission',
      'modificationModeActive': 'Edit mode activated',
      'studentsNotFound': 'No students found.',
      'operationSuccess': 'Operation successful!',
      'dashboardComptable': 'Accountant Dashboard',
      'dashboardEnseignant': 'Teacher Dashboard',
      'dashboardFondateur': 'Founder Dashboard',
      'dashboardSecretaire': 'Secretary Dashboard',
      'dashboardSurveillantGeneral': 'General Supervisor Dashboard',
      'dashboardProviseur': 'Principal Dashboard',
      'activityUpdatedSchedule': 'Schedule updated',
      'activityBulletinValidated': 'Report card validated',
      'activityAbsencesToProcess': 'Absences to process',
      'logout': 'Logout',
      'appel': 'Take Attendance',
      'recapYears': 'Academic Years Recap',
      'bulletins': 'Report Cards',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? _localizedValues['fr']![key] ?? key;
  }
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['fr', 'en'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
