import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static const supportedLocales = [Locale('fr'), Locale('en')];

  static AppLocalizations of(BuildContext context) {
    final AppLocalizations? instance = Localizations.of<AppLocalizations>(
      context,
      AppLocalizations,
    );
    assert(instance != null, 'No AppLocalizations found in context');
    return instance!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const Map<String, Map<String, String>> _localizedValues = {
    'fr': {
      'appTitle': 'EduGest',
      'welcomeTitle': 'Bienvenue sur EduGest',
      'welcomeDescription':
          'Une application pour gérer vos données scolaires facilement.',
      'getStarted': 'Commencer',
      'loginTitle': 'Se connecter',
      'loginSubtitle': 'Accédez à votre espace de gestion scolaire.',
      'chooseRole': 'CHOISISSEZ VOTRE RÔLE',
      'connectButton': 'Se connecter',
      'settingsTitle': 'Paramètres de l\'application',
      'preferences': 'Préférences',
      'fullName': 'Nom complet',
      'emailAddress': 'Adresse e-mail',
      'nameRequired': 'Veuillez renseigner votre nom',
      'emailRequired': 'Veuillez renseigner votre e-mail',
      'notificationsActive': 'Notifications actives',
      'applicationLanguage': 'Langue de l\'application',
      'savePreferences': 'Sauvegarder les préférences',
      'preferencesSaved': 'Préférences sauvegardées avec succès.',
      'support': 'Support',
      'helpCenter': 'Centre d\'aide',
      'privacyPolicy': 'Politique de confidentialité',
      'languageFrench': 'Français',
      'languageEnglish': 'Anglais',
      'emailHint': 'Adresse email',
      'passwordHint': 'Mot de passe',
      'principal': 'Principal',
      'schoolLife': 'Vie Scolaire',
      'administration': 'Administration',
      'dashboard': 'Tableau de bord',
      'timetable': 'Emploi du temps',
      'students': 'Élèves',
      'teachers': 'Enseignants',
      'myNotes': 'Mes Notes',
      'myNotebook': 'Mon Cahier de Texte',
      'adminAnnouncements': 'Annonces Admin',
      'receptionNotes': 'Réception Notes',
      'receptionNotebooks': 'Réception Cahiers',
      'programTracking': 'Suivi du programme',
      'teacherRoomChecks': 'Présence des professeurs',
      'events': 'Événements',
      'discipline': 'Discipline',
      'managementStaff': 'Gestion Staff',
      'payments': 'Paiements',
      'expenses': 'Dépenses',
      'classes': 'Classes',
      'subjects': 'Matières',
      'settings': 'Paramètres',
      'profile': 'Profil',
      'account': 'Compte',
      'overviewWelcome': 'Bienvenue dans votre espace EduGest',
      'overviewSelectMenu': 'Sélectionnez un menu à gauche pour commencer',
      'dashboardTitle': 'Pilotage Établissement',
      'staffActivity': 'Activités récentes du staff',
      'effectif': 'Effectif',
      'successRate': 'Réussite',
      'revenue': 'Recettes',
      'planningEvents': 'Planning & Événements',
      'add': 'Ajouter',
      'newEvent': 'Nouvel Événement',
      'title': 'Titre',
      'category': 'Catégorie',
      'dateLabel': 'Date',
      'timeLabel': 'Heure',
      'cancel': 'Annuler',
      'searchPlaceholder': 'Rechercher...',
      'noEvents': 'Aucun événement',
      'all': 'Tous',
      'council': 'Conseil',
      'exam': 'Examen',
      'meeting': 'Réunion',
      'ceremony': 'Cérémonie',
      'absenceTracking': 'Suivi des Absences',
      'report': 'Signaler',
      'today': 'Aujourd\'hui',
      'thisWeek': 'Cette semaine',
      'thisMonth': 'Ce mois',
      'studentName': 'Élève Nom',
      'classLabel': 'Classe',
      'justified': 'Justifiée',
      'lessonBook': 'Cahier de Texte',
      'lessonEditing': 'Modification de la Leçon',
      'entryTab': 'Saisie',
      'myPosts': 'Mes Publications',
      'editingMode': 'Mode Modification',
      'classConcerned': 'Classe concernée',
      'detailedContent': 'Contenu détaillé',
      'lessonTitleHint': 'Titre de la leçon',
      'lessonDetailHint': 'Détaillez le cours ici...',
      'publishLesson': 'Publier la leçon',
      'updateLesson': 'Mettre à jour',
      'lessonSavedSuccess': 'Leçon enregistrée avec succès !',
      'notesManagement': 'Gestion des Notes',
      'notesEdition': 'Modification des Notes',
      'mySubmissions': 'Mes Envois',
      'sendToAdmin': 'Envoyer à l\'administration',
      'updateSubmission': 'Mettre à jour l\'envoi',
      'modificationModeActive': 'Mode Modification activé',
      'studentsNotFound': 'Aucun élève trouvé.',
      'operationSuccess': 'Opération réussie !',
      'dashboardComptable': 'Tableau de bord Comptable',
      'dashboardEnseignant': 'Tableau de bord Enseignant',
      'dashboardFondateur': 'Tableau de bord Fondateur',
      'dashboardSecretaire': 'Tableau de bord Secrétaire',
      'dashboardSurveillantGeneral': 'Tableau de bord Surveillant Général',
      'dashboardProviseur': 'Tableau de bord Proviseur',
      'activityUpdatedSchedule': 'Emploi du temps mis à jour',
      'activityBulletinValidated': 'Bulletin validé',
      'activityAbsencesToProcess': 'Absences à traiter',
      'logout': 'Déconnexion',
      'appel': 'Faire l\'appel',
      'recapYears': 'Récapitulatif Années',
      'bulletins': 'Bulletins Scolaires',
      'auditLogs': 'Journal d\'audit',
      'schoolLifeAndPedagogy': 'Vie Scolaire',
      'communication': 'Communication',
      'takeAttendance': 'Faire l\'appel',
      'teacherList': 'Liste Enseignants',
      'notesAndAssessments': 'Notes & Évaluations',
      'notificationsAndAnnouncements': 'Notifications & Annonces',
      'notesForChildren': 'Mes Notes / Enfants',
      'disciplineAndSanctions': 'Discipline & Sanctions',
      'schoolAbsences': 'Absences',
      'schoolStaffManagement': 'Gestion du Staff',
      'schoolPayments': 'Paiements Scolaires',
      'financialDashboard': 'Tableau de Bord Financier',
      'classManagement': 'Gestion des Classes',
      'subjectManagement': 'Gestion des Matières',
      'myProfile': 'Mon Profil',
      'createAccount': 'Créer un compte',
      'alreadyHaveAccount': 'Déjà un compte ? Se connecter',
      'accountCreated': 'Créer le compte',
      'fullNameHint': 'Nom complet',
      'contactPhone': 'Téléphone de contact',
      'signupDescription':
          'Créez votre compte. Vous pourrez rejoindre une école avec son code.',
      'loginCredentialsRequired':
          'Identifiant (email ou téléphone) et mot de passe requis',
      'saveInProgress': 'Sauvegarde en cours...',
      'developerCredit': 'Développé par One\'s Company',
      'schoolSettings': 'Paramètres de l\'établissement & année académique',
      'openNewYear': 'Ouvrir une nouvelle année',
      'notConnected': 'Non connecté',
      'pleaseLogin': 'Veuillez vous connecter',
      'mySchools': 'Mes établissements',
      'schoolLoadingError': 'Erreur lors du chargement des écoles.',
      'noSchoolMembership': 'Vous n\'êtes inscrit dans aucune école.',
      'joinOrCreateSchool': 'Rejoindre ou créer une école',
      'selectSchoolToManage': 'Sélectionnez l\'établissement à gérer :',
      'undefinedAddress': 'Adresse non définie',
      'addAnotherSchool': 'Ajouter un autre établissement',
      'selectionError': 'Erreur de sélection',
      'academicYear': 'Année',
      'managementSystem': 'Système de gestion',
      'teachersOnlySubmitGrades':
          'Seuls les enseignants peuvent envoyer des notes.',
      'confirmCloseYear':
          'Voulez-vous sauvegarder et archiver immédiatement la session',
      'closeYearDescription':
          '• Un récapitulatif consolidé complet sera généré et enregistré dans la page de la fondatrice.\n'
          '• Le système sera mis en attente de la nouvelle année académique.',
      'yearArchivedSuccess': 'Année sauvegardée et archivée avec succès',
      'errorPrefix': 'Erreur :',
      'newYearDescription':
          'Saisissez les informations de la nouvelle session scolaire à démarrer :',
      'startDate': 'Date de début',
      'downloadPdfReport': 'Télécharger le rapport PDF',
      'annualReview': 'Bilan annuel',
      'schoolLabel': 'Établissement',
      'periodLabel': 'Période',
      'savedAndClosedOn': 'Sauvegardé et clôturé le :',
      'financialSection': '1. Volet financier',
      'totalRevenue': 'Recettes totales :',
      'totalExpenses': 'Dépenses totales :',
      'netBalance': 'Solde net d’exercice :',
      'academicSection': '2. Volet pédagogique',
      'enrolledStudentsLabel': 'Élèves inscrits :',
      'activeTeachersLabel': 'Enseignants actifs :',
      'lessonsLabel': 'Séances de cours :',
      'organizedExamsLabel': 'Examens organisés :',
      'disciplineSection': '3. Volet discipline',
      'totalAbsences': 'Total des absences :',
      'totalSanctions': 'Total des sanctions :',
      'printPdf': 'Imprimer le PDF',
      'options': 'Options :',
      'examClassesTracking': 'Suivi des classes d’examen',
      'completeFile': 'Dossier complet',
      'incompleteFile': 'Dossier incomplet',
      'completeFees': 'Frais complets',
      'fees': 'Frais',
      'officialFee': 'officiel',
      'parentChildrenLoadError':
          'Impossible de charger les informations de vos enfants.',
      'noChildren': 'Aucun enfant n’est associé à ce compte Parent.',
      'parentReadOnly': 'Consultez uniquement les informations de vos enfants.',
      'parentExamLoadError':
          'Impossible de charger le statut d’examen de cet enfant.',
      'parentExamComplete':
          'Le dossier et les frais de {student} sont complets.',
      'parentExamIncomplete':
          'Le dossier de {student} doit encore être complété.',
      'statusUpToDate': 'STATUT : À JOUR',
      'statusNotUpToDate': 'STATUT : NON À JOUR',
      'noPublishedBulletin': 'Aucun bulletin publié pour',
      'bulletinPendingPublication':
          'Le bulletin apparaîtra ici uniquement après publication par le proviseur ou la secrétaire.',
      'bulletinPdfError': 'Impossible de générer le bulletin PDF :',
      'staffRegistrationTitle': 'Inscription du personnel',
      'staffRecruitmentForbidden':
          'Vous n’avez pas l’autorisation de recruter un membre du personnel.',
      'professionalEmail': 'E-mail professionnel (identifiant)',
      'staffAccountCreated': 'Le compte a été créé avec succès pour',
      'staffFieldsRequired':
          'Veuillez renseigner le nom, le téléphone, l’e-mail et le mot de passe.',
      'staffSignupDescription':
          'Créez les comptes d’accès des membres de votre établissement.',
      'createStaffAccount': 'Créer le compte du personnel',
      'assignedPosition': 'Poste attribué',
      'schoolLevelPrimary': 'Primaire',
      'schoolLevelCollege': 'Collège',
      'schoolLevelLycee': 'Lycée',
    },
    'en': {
      'appTitle': 'EduGest',
      'welcomeTitle': 'Welcome to EduGest',
      'welcomeDescription': 'An app for managing your school data with ease.',
      'getStarted': 'Get Started',
      'loginTitle': 'Sign In',
      'loginSubtitle': 'Access your school management dashboard.',
      'chooseRole': 'CHOOSE YOUR ROLE',
      'connectButton': 'Sign In',
      'settingsTitle': 'Application Settings',
      'preferences': 'Preferences',
      'fullName': 'Full Name',
      'emailAddress': 'Email Address',
      'nameRequired': 'Please enter your name',
      'emailRequired': 'Please enter your email',
      'notificationsActive': 'Active Notifications',
      'applicationLanguage': 'Application Language',
      'savePreferences': 'Save Preferences',
      'preferencesSaved': 'Preferences saved successfully.',
      'support': 'Support',
      'helpCenter': 'Help Center',
      'privacyPolicy': 'Privacy Policy',
      'languageFrench': 'French',
      'languageEnglish': 'English',
      'emailHint': 'Email address',
      'passwordHint': 'Password',
      'principal': 'Main',
      'schoolLife': 'School Life',
      'administration': 'Administration',
      'dashboard': 'Dashboard',
      'timetable': 'Timetable',
      'students': 'Students',
      'teachers': 'Teachers',
      'myNotes': 'My Notes',
      'myNotebook': 'My Notebook',
      'adminAnnouncements': 'Admin Announcements',
      'receptionNotes': 'Notes Reception',
      'receptionNotebooks': 'Notebook Reception',
      'programTracking': 'Program tracking',
      'teacherRoomChecks': 'Teacher presence',
      'events': 'Events',
      'discipline': 'Discipline',
      'managementStaff': 'Staff Management',
      'payments': 'Payments',
      'expenses': 'Expenses',
      'classes': 'Classes',
      'subjects': 'Subjects',
      'settings': 'Settings',
      'profile': 'Profile',
      'account': 'Account',
      'overviewWelcome': 'Welcome to your EduGest workspace',
      'overviewSelectMenu': 'Select a menu on the left to begin',
      'dashboardTitle': 'School Management',
      'staffActivity': 'Recent staff activity',
      'effectif': 'Student body',
      'successRate': 'Success rate',
      'revenue': 'Revenue',
      'planningEvents': 'Planning & Events',
      'add': 'Add',
      'newEvent': 'New Event',
      'title': 'Title',
      'category': 'Category',
      'dateLabel': 'Date',
      'timeLabel': 'Time',
      'cancel': 'Cancel',
      'searchPlaceholder': 'Search...',
      'noEvents': 'No events',
      'all': 'All',
      'council': 'Council',
      'exam': 'Exam',
      'meeting': 'Meeting',
      'ceremony': 'Ceremony',
      'absenceTracking': 'Absence Tracking',
      'report': 'Report',
      'today': 'Today',
      'thisWeek': 'This week',
      'thisMonth': 'This month',
      'studentName': 'Student Name',
      'classLabel': 'Class',
      'justified': 'Justified',
      'lessonBook': 'Lesson Notebook',
      'lessonEditing': 'Lesson Editing',
      'entryTab': 'Entry',
      'myPosts': 'My Posts',
      'editingMode': 'Edit Mode',
      'classConcerned': 'Class',
      'detailedContent': 'Detailed content',
      'lessonTitleHint': 'Lesson title',
      'lessonDetailHint': 'Describe the lesson here...',
      'publishLesson': 'Publish lesson',
      'updateLesson': 'Update',
      'lessonSavedSuccess': 'Lesson saved successfully!',
      'notesManagement': 'Notes Management',
      'notesEdition': 'Notes Editing',
      'mySubmissions': 'My Submissions',
      'sendToAdmin': 'Send to administration',
      'updateSubmission': 'Update submission',
      'modificationModeActive': 'Edit mode activated',
      'studentsNotFound': 'No students found.',
      'operationSuccess': 'Operation successful!',
      'dashboardComptable': 'Accountant Dashboard',
      'dashboardEnseignant': 'Teacher Dashboard',
      'dashboardFondateur': 'Founder Dashboard',
      'dashboardSecretaire': 'Secretary Dashboard',
      'dashboardSurveillantGeneral': 'General Supervisor Dashboard',
      'dashboardProviseur': 'Principal Dashboard',
      'activityUpdatedSchedule': 'Schedule updated',
      'activityBulletinValidated': 'Report card validated',
      'activityAbsencesToProcess': 'Absences to process',
      'logout': 'Logout',
      'appel': 'Take Attendance',
      'recapYears': 'Academic Years Recap',
      'bulletins': 'Report Cards',
      'auditLogs': 'Audit Log',
      'schoolLifeAndPedagogy': 'School Life',
      'communication': 'Communication',
      'takeAttendance': 'Take Attendance',
      'teacherList': 'Teacher List',
      'notesAndAssessments': 'Notes & Assessments',
      'notificationsAndAnnouncements': 'Notifications & Announcements',
      'notesForChildren': 'My Notes / Children',
      'disciplineAndSanctions': 'Discipline & Sanctions',
      'schoolAbsences': 'Absences',
      'schoolStaffManagement': 'Staff Management',
      'schoolPayments': 'School Payments',
      'financialDashboard': 'Financial Dashboard',
      'classManagement': 'Class Management',
      'subjectManagement': 'Subject Management',
      'myProfile': 'My Profile',
      'createAccount': 'Create an account',
      'alreadyHaveAccount': 'Already have an account? Sign in',
      'accountCreated': 'Create account',
      'fullNameHint': 'Full name',
      'contactPhone': 'Contact phone',
      'signupDescription':
          'Create your account. You can join a school using its code.',
      'loginCredentialsRequired':
          'Email or phone number and password are required',
      'saveInProgress': 'Saving...',
      'developerCredit': 'Developed by One\'s Company',
      'schoolSettings': 'School & academic year settings',
      'openNewYear': 'Open new year',
      'notConnected': 'Not signed in',
      'pleaseLogin': 'Please sign in',
      'mySchools': 'My schools',
      'schoolLoadingError': 'Unable to load schools.',
      'noSchoolMembership': 'You are not registered with any school.',
      'joinOrCreateSchool': 'Join or create a school',
      'selectSchoolToManage': 'Select the school to manage:',
      'undefinedAddress': 'Address not defined',
      'addAnotherSchool': 'Add another school',
      'selectionError': 'Selection error',
      'academicYear': 'Academic year',
      'managementSystem': 'Management system',
      'showPassword': 'Show password',
      'hidePassword': 'Hide password',
      'absenceSlipProcessing': 'Absence slip processing',
      'annualSchoolReport': 'Annual school report',
      'appreciation': 'Comments',
      'cashReport': 'Cash report',
      'contactSchool': 'Contact the school',
      'courseProgram': 'Course program',
      'criticalRolesManagement': 'Critical role management',
      'dailyConductReport': 'Daily conduct report',
      'disciplineControl': 'Discipline control',
      'enterQuizGrades': 'Enter quiz grades',
      'evaluation': 'Assessment',
      'fillLessonBook': 'Fill the lesson notebook',
      'financeConsolidation': 'Financial consolidation',
      'financialSituation': 'Financial situation',
      'globalRevenue': 'Global revenue',
      'gradeEntryClosure': 'Close grade entry',
      'lessonBookControl': 'Lesson notebook control',
      'morningAttendance': 'Morning class attendance',
      'open': 'Open',
      'paymentRecording': 'Payment recording',
      'previousYearClosed':
          'The previous year was closed. Go to Settings to start the new academic year.',
      'publishedBy': 'Published by',
      'publishedOn': 'Published on',
      'reportCardsValidation': 'Report card validation in progress',
      'selected': 'Selected',
      'staffMembers': 'Staff members',
      'supplierPayments': 'Supplier payments',
      'teacherStaffReview': 'Teacher staff review',
      'timetableVerification': 'Timetable verification',
      'toReview': 'To review',
      'totalStudents': 'Total students',
      'yearWaitingRenewal': 'School year saved and archived ? awaiting renewal',
      'auditCategory_tous': 'All actions',
      'auditCategory_note': 'Grades',
      'auditCategory_cahier_texte': 'Lesson notebook',
      'auditCategory_paiement': 'Payments',
      'auditCategory_bulletin': 'Report cards',
      'auditCategory_evaluation': 'Assessments',
      'auditCategory_depense': 'Expenses',
      'selectStudentForTuition':
          'Search for the student first: the class tuition is suggested automatically.',
      'performedBy': 'Performed by',
      'staffDeleted': 'Staff member deleted successfully.',
      'missingGradesDetected': 'Missing grades detected',
      'invalidCoefficients': 'Zero or undefined coefficients',
      'allGradesRequiredBeforePublish':
          'All assessments for the period must be graded with non-zero coefficients before publishing.',
      'completeGradesBeforePublish':
          'Please complete all grades and coefficients before official publication.',
      'understood': 'Understood',
      'confirmPublication': 'Confirm publication',
      'noMissingGrades': 'No missing grades detected',
      'validCoefficients': 'All coefficients are valid (> 0)',
      'parentsNotifiedBulletin':
          'Parents will be notified and can immediately view and download the report card PDF.',
      'confirmAndPublish': 'Confirm & publish',
      'remove': 'Remove',
      'bulletinsUnpublished': 'Report cards removed from the Parent portal.',
      'bulletinsPublished':
          'Report cards published successfully: parents can now view and download them.',
      'publicationUpdateError': 'Unable to update publication:',
      'noClassesConfigured': 'No class configured in the school.',
      'currentSession': 'Current session',
      'reportCardGeneration': 'Report card generation',
      'officialReportCardsDescription':
          'Official report cards with subject grades, weighted averages, ranking, and absence hours',
      'generationInProgress': 'Generating...',
      'printEntireClass': 'Print entire class',
      'updateInProgress': 'Updating...',
      'publishToParents': 'Publish to parents',
      'removeFromParents': 'Remove from parents',
      'printAllReportCards': 'Print all report cards',
      'classAverage': 'Class average',
      'minMaxGrade': 'Min / max grade',
      'includedExams': 'Included exams',
      'studentList': 'Student list',
      'studentId': 'Student ID',
      'rank': 'Rank',
      'reportCardPreview': 'Report card preview',
      'downloadPrintReportCard': 'Download / print this report card',
      'gradesAndCoefficients': 'Grades & coefficients details:',
      'notGraded': 'Not graded',
      'termResult': 'Term result',
      'overallAverage': 'Overall average:',
      'classRank': 'Class rank',
      'outOf': 'out of',
      'recordedIncidents': 'Recorded incidents',
      'excellentAttendance': 'Excellent attendance',
      'satisfactoryAttendance': 'Satisfactory attendance',
      'attendanceNeedsMonitoring': 'Attendance needs monitoring',
      'schoolLifeAndAbsences': 'School life & absences',
      'hours': 'hour(s)',
      'min': 'Min',
      'max': 'Max',
      'actionCreate': 'Creation',
      'actionUpdate': 'Update',
      'actionDelete': 'Deletion',
      'actionPublish': 'Publication',
      'actionUnpublish': 'Unpublication',
      'actionExport': 'Export',
      'actionImport': 'Import',
      'archivedYears': 'Archived years',
      'assignedPosition': 'Assigned position',
      'auditLogDescription':
          'Full traceability of creations, changes, and deletions',
      'auditLogEmptyDescription':
          'Grade, lesson notebook, payment, and publication operations will appear here.',
      'auditLogLoadError': 'Error loading audit log:',
      'auditLogSearch': 'Search by author, description, student, subject...',
      'auditLogTitle': 'Audit log & action history',
      'noAuditActions': 'No action recorded for these criteria.',
      'changePassword': 'Change password',
      'collected': 'Collected',
      'collectedBy': 'Collected by',
      'createStaffAccount': 'Create staff account',
      'staffRegistrationTitle': 'Staff registration',
      'staffRecruitmentForbidden':
          'You are not allowed to recruit a staff member.',
      'professionalEmail': 'Professional email (login)',
      'schoolLevelPrimary': 'Primary',
      'schoolLevelCollege': 'Middle school',
      'schoolLevelLycee': 'High school',
      'generateStandardReceipt': 'Generate standard PDF receipt (A5)',
      'parentExamUnavailable':
          'This child is not enrolled in an exam class or no exam is configured yet.',
      'parentPasswordFallback':
          'If left empty, the parent?s number will be used as the temporary password.',
      'passwordCodeDescription':
          'A code valid for 15 minutes will be sent by email or WhatsApp.',
      'preview': 'Preview',
      'receiptPrinting': 'Printing receipt',
      'recentPayments': 'Recent payments',
      'recordSchoolFees': 'Record school fees',
      'role': 'Role',
      'schoolFees': 'School fees',
      'schoolFeesAndCollections': 'School fees & collections',
      'security': 'Security',
      'selectStudentAmount': 'Select an existing student and an amount.',
      'signupFormDescription':
          'Enter your name, an email or phone number, and a password of at least 6 characters.',
      'simplePayment': 'Simple payment',
      'staffAccountCreated': 'The account was created successfully!',
      'staffFieldsRequired':
          'Please enter the name, phone, email, and password.',
      'staffSignupDescription':
          'Create access accounts for your administration members.',
      'standardReceiptDescription': 'A5 payment receipt with signature box',
      'teacherAccountCreated':
          'Account created. The teacher must use ?Forgot password? to activate access.',
      'teacherFieldsRequired':
          'Please enter the name, phone, email, and specialty.',
      'gradesPreview': 'Grades preview',
      'teacherOnlyGrades':
          'View only: grade entry and editing are reserved for teachers.',
      'lockedEditing': 'Editing locked',
      'noClassesVerify': 'No classes available. Check the registered classes.',
      'noStudentsEnrolledIn': 'No student enrolled in',
      'sequence': 'Sequence',
      'subscriptionPayment': 'Pay your EduGest subscription',
      'subscriptionPaymentDescription':
          'Deposit the payment to one of the numbers below, then contact administration for validation.',
      'subscriptionValidUntil': 'Subscription valid until',
      'scheduledSaveCloseDate': 'Scheduled save and closure date',
      'newAcademicYearStarted': 'New academic year opened successfully',
      'startYear': 'Start the year',
      'previousYearArchived': 'Previous school year saved and closed',
      'previousYearArchivedDescription':
          'All past operations are archived on the Recap page. Enter and start the new school year to resume entries.',
      'schoolNameLabel': 'School name / Institution',
      'schoolYearLabel': 'School year / Session (e.g. 2024-2025)',
      'cycleManagement': 'Cycle and automatic save management:',
      'yearStartDate': 'School year start date',
      'notDefined': 'Not defined',
      'saveCloseDate': 'Save and closure date',
      'saveCloseInfo':
          '?? On the save date, all school year data will be stored in the founder recap and the app will wait for the new year to open.',
      'addressLocation': 'Address / Location',
      'officialEmail': 'Official email',
      'closingInProgress': 'Closing...',
      'saveAndCloseNow': 'Save & close the year now',
      'newSchoolYear': 'New school year',
      'pastYearsRecap': 'Past years recap',
      'founderRecapDescription':
          'Founder space ? consolidated review, statistics, and archives of previous sessions',
      'noArchivedYears': 'No school year archived',
      'noArchivedYearsDescription':
          'Recaps will appear here automatically when a school year is saved and closed in Settings.',
      'mySchool': 'My school',
      'session': 'Session',
      'archived': 'ARCHIVED',
      'closedOn': 'Closed on',
      'officialPeriod': 'Official period',
      'studentCount': 'Student count',
      'courses': 'courses',
      'exams': 'exams',
      'notesReceptionValidation': 'Grades reception & validation',
      'noExamSubmission': 'No exam submission found for this class.',
      'sentBy': 'Sent by',
      'noPublishedAnnouncements':
          'No announcement or event published at the moment.',
      'courseTrackingDescription':
          'Find published lessons and program progress in one place.',
      'teacherRoomPresence': 'Teacher room presence',
      'reportedAbsencesJustification':
          'Your reported absences and their justification deadline',
      'lessonsVerified': 'lessons verified',
      'absenceReportedOn': 'Absence reported on',
      'justificationBefore': 'Justification due by',
      'justificationSent': 'Justification sent',
      'verifiedAt': 'verified at',
      'by': 'by',
      'selectSubject': 'Select a subject',
      'completedChapters': 'Completed chapters',
      'parentCompletedChaptersDescription':
          'Main chapters completed by your children?s teachers.',
      'teacherProgramDescription':
          'Add your main chapters, then mark them complete.',
      'programTrackingDescription':
          'Track program progress by class, subject, and teacher.',
      'completedOn': 'Completed on',
      'courseTracking': 'Course tracking',
      'tuitionTracking': 'Tuition tracking',
      'examClasses': 'Exam classes',
      'programProgress': 'Program and progress',
      'selectStudentReason':
          'Select an existing student and provide the reason.',
      'editEvent': 'Edit event',
      'teachersOnlySubmitGrades': 'Only teachers can submit grades.',
      'confirmCloseYear':
          'Do you want to save and archive the session immediately',
      'closeYearDescription':
          '• A complete consolidated recap will be generated and saved on the founder page.\n'
          '• The system will wait for the new academic year.',
      'yearArchivedSuccess': 'Year saved and archived successfully',
      'errorPrefix': 'Error:',
      'newYearDescription':
          'Enter the information for the new school year to start:',
      'startDate': 'Start date',
      'downloadPdfReport': 'Download PDF report',
      'annualReview': 'Annual review',
      'schoolLabel': 'School',
      'periodLabel': 'Period',
      'savedAndClosedOn': 'Saved and closed on:',
      'financialSection': '1. Financial section',
      'totalRevenue': 'Total revenue:',
      'totalExpenses': 'Total expenses:',
      'netBalance': 'Net operating balance:',
      'academicSection': '2. Academic section',
      'enrolledStudentsLabel': 'Enrolled students:',
      'activeTeachersLabel': 'Active teachers:',
      'lessonsLabel': 'Lessons:',
      'organizedExamsLabel': 'Organized exams:',
      'disciplineSection': '3. Discipline section',
      'totalAbsences': 'Total absences:',
      'totalSanctions': 'Total sanctions:',
      'printPdf': 'Print PDF',
      'verification': 'Verification',
      'verificationCodeLength': 'The code must contain 6 characters.',
      'passwordValidation':
          'Passwords must match and contain at least 6 characters.',
      'verificationSuccess': 'Operation confirmed. You can sign in.',
      'verificationCodeTitle': 'Verification code',
      'verificationCodeDescription':
          'A 6-character code was sent primarily by email, or by WhatsApp if needed. It is valid for 15 minutes.',
      'newPassword': 'New password',
      'confirmPassword': 'Confirm password',
      'validateCode': 'Validate code',
      'classNotProvided': 'Class not provided',
      'tuitionTrackingByClass': 'Tuition tracking by class',
      'tuitionTrackingDescription':
          'Actual status of students who are up to date and those who still have a balance due.',
      'noStudentsRegistered': 'No students registered.',
      'withBalance': 'with a balance',
      'tuitionCompleted': 'Tuition paid in full',
      'remainingToPay': 'Remaining to pay:',
      'toPay': 'TO PAY',
      'attendanceSent': 'Attendance was sent.',
      'absentCount': 'Number absent',
      'ok': 'OK',
      'teachersOnlyAttendance': 'Only teachers can take attendance.',
      'noClassAtTime': 'No lesson is scheduled at this time.',
      'checkTimetableClock': 'Check your timetable or your computer clock.',
      'noStudentsInClassPrefix': 'No students found for class',
      'checkClassNameAttendance':
          'Check that the class name in the timetable exactly matches the one used in the \'Students\' menu.',
      'attendanceList': 'Attendance list',
      'absent': 'Absent',
      'schoolCodeRequired': 'Please enter the school code.',
      'schoolJoined': 'You joined this school.',
      'schoolNameCodeRequired': 'Please enter the school name and code.',
      'accessSchool': 'Access a school',
      'accessSchoolDescription':
          'Use the code provided by your school or create your own school.',
      'assignedRole': 'Assigned role',
      'schoolCode': 'School code',
      'joinByCode': 'Join by code',
      'loadEventsError': 'Error loading events',
      'attendanceCompleted': 'Attendance completed',
      'allPresent': 'Everyone present',
      'bulletinGenerationError': 'Report card generation error:',
      'publicationBlocked': 'Publication blocked',
      'noAbsencesToJustify': 'No absences to justify.',
      'noClassToday': 'No lesson scheduled today.',
      'present': 'Present',
      'noGrades': 'No grades recorded.',
      'downloadPdf': 'Download PDF',
      'downloadExcel': 'Download Excel',
      'passwordUpdated': 'Password updated successfully',
      'viewDetails': 'View details',
      'forgotPassword': 'Forgot password',
      'emailOrPhone': 'Email or phone number',
      'sixCharacterCode': '6-character code',
      'newSchoolName': 'New school name',
      'privateSchoolCode': 'School private code',
      'createSchool': 'Create school',
      'examClassesTracking': 'Exam class tracking',
      'completeFile': 'Complete file',
      'incompleteFile': 'Incomplete file',
      'completeFees': 'Complete fees',
      'fees': 'Fees',
      'officialFee': 'official',
      'parentChildrenLoadError': 'Unable to load your children’s information.',
      'noChildren': 'No child is associated with this parent account.',
      'parentReadOnly': 'View your children’s information only.',
      'parentExamLoadError': 'Unable to load this child’s exam status.',
      'parentExamComplete': '{student}’s file and fees are complete.',
      'parentExamIncomplete': '{student}’s file still needs to be completed.',
      'statusUpToDate': 'STATUS: UP TO DATE',
      'statusNotUpToDate': 'STATUS: NOT UP TO DATE',
      'noPublishedBulletin': 'No report card published for',
      'bulletinPendingPublication':
          'The report card will appear here after publication by the principal or secretary.',
      'bulletinPdfError': 'Unable to generate the report card PDF:',
      'auto_vie_scolaire': 'School life',
      'auto_communication': 'Communication',
      'auto_consulter_vos_informations': 'View your information',
      'auto_appliquer': 'Apply',
      'auto_enseignant': 'Teacher',
      'auto_titre': 'Title',
      'auto_enfant': 'Child',
      'auto_email': 'Email',
      'auto_absent': 'Absent',
      'auto_voulez_vous_publier_les_bulletins_de_la_classe_s':
          'Voulez vous publish the bulletins of the class selectedclass for the period selectedperiod',
      'auto_retirer_la_publication': 'Retirer the publication',
      'auto_voulez_vous_masquer_les_bulletins_de_la_classe_s':
          'Voulez vous masquer the bulletins of the class selectedclass for the period selectedperiod the parents ne pourront plus y acceder',
      'auto_mot_de_passe_oublie': 'Mot of passe oublie',
      'auto_voulez_vous_telecharger_le_bordereau':
          'Voulez vous telecharger the bordereau',
      'auto_': '',
      'auto_null': 'Null',

      'loadAbsencesError': 'Error loading absences',
      'fullDay': 'Full day',
      'morning': 'Morning',
      'afternoon': 'Afternoon',
      'reportAbsence': 'Report an absence',
      'studentNameHint': 'Student name',
      'period': 'Period',
      'reason': 'Reason',
      'notJustified': 'Not justified',
      'saveError': 'Save error',
      'noAbsences': 'No absences reported.',
      'lessonBookUpdated': 'Lesson notebook updated!',
      'lessonBookPreview': 'Lesson notebook preview',
      'teacherOnlyLessonBook':
          'View only: writing and publishing are reserved for teachers.',
      'subject': 'Subject',
      'update': 'Update',
      'noPublishedLessons': 'No lessons published.',
      'selectClassSubject': 'Select a class and a subject',
      'loadExpensesError': 'Error loading expenses',
      'newExpense': 'New expense',
      'label': 'Label',
      'amount': 'Amount',
      'optionalDescription': 'Description (optional)',
      'save': 'Save',
      'expenseManagement': 'Expense Management',
      'noExpenses': 'No expenses recorded',
      'recordedBy': 'Recorded by:',
      'loadClassesError': 'Error loading classes',
      'createClass': 'Create a class',
      'classNameExample': 'Name (e.g. 6th A)',
      'levelExample': 'Level (e.g. 6th)',
      'capacity': 'Capacity',
      'tuitionFees': 'Tuition / school fees (FCFA)',
      'description': 'Description',
      'examClass': 'Exam class',
      'enableExamTracking': 'Enable exam file and fee tracking',
      'create': 'Create',
      'noClassesCreate': 'No classes. Create one.',
      'configureExam': 'Configure exam',
      'loadSubjectsError': 'Error loading subjects',
      'addSubject': 'Add a subject',
      'editSubject': 'Edit subject',
      'subjectNameExample': 'Subject name (e.g. Mathematics)',
      'coefficient': 'Coefficient',
      'validate': 'Validate',
      'noSubjects': 'No subjects recorded.',
      'delete': 'Delete',
      'confirmDeleteSubject': 'Do you really want to delete subject',
      'no': 'No',
      'yes': 'Yes',
      'loadStaffError': 'Error loading staff',
      'noStaff': 'No staff member found.',
      'confirm': 'Confirm',
      'loadTeachersError': 'Error loading teachers',
      'specialty': 'Specialty (Subject)',
      'phoneRequired': 'Phone *',
      'emailIdentifier': 'Email (Login)',
      'temporaryPassword': 'Temporary password',
      'searchTeacher': 'Search for a teacher...',
      'noTeachers': 'No teachers found.',
      'studentInformation': 'Student information',
      'firstName': 'First name',
      'lastName': 'Last name',
      'birthDate': 'Date of birth',
      'selectClass': 'Select a class',
      'parentInformation': 'Parent information',
      'parentName': 'Parent name',
      'parentPhone': 'Parent phone',
      'parentEmail': 'Parent email',
      'parentTemporaryPassword': 'Parent temporary password (optional)',
      'noClassesAvailable': 'No classes available. Create one first.',
      'registerStudent': 'Register a student',
      'editStudent': 'Edit student',
      'studentFieldsRequired':
          'Please fill in the last name, first name, and select a class',
      'studentManagement': 'Student Management',
      'searchStudent': 'Search for a student...',
      'noStudents': 'No students found.',
      'bornOn': 'Born on:',
      'parent': 'Parent:',
      'registeredBy': 'Registered by:',
      'subjectColon': 'Subject:',
      'options': 'Options:',
      'downloadSlip': 'Would you like to download the statement?',
      'loadDetailsError': 'Error loading details',
      'teachersOnlyEditGrades': 'Only teachers can edit grades.',
      'gradesLocked': 'This entry is locked after 7 days.',
      'editGrades': 'Edit grades',
      'saveGrades': 'Save grades',
      'gradesSaved': 'Grades saved successfully!',
      'noHistory': 'No history available.',
      'retry': 'Retry',
      'loadPaymentsError': 'Error loading payments',
      'searchExistingStudent': 'Search for an existing student',
      'nameOrId': 'Name or ID',
      'payerStudent': 'Payer / student name',
      'paymentSaved': 'Payment saved successfully',
      'ticket80': '80mm TICKET',
      'noPayments': 'No payments',
      'thermalTicket': 'Thermal ticket (80mm roll)',
      'standardPdfReceipt': 'Standard PDF receipt (A5)',
      'loadScheduleError': 'Error loading timetable',
      'addTimeSlot': 'Add a time slot',
      'start': 'Start',
      'end': 'End',
      'missingFields': 'Missing fields',
      'noLessonsToday': 'No lessons scheduled for this day.',
      'sanctionType': 'Sanction type',
      'noIncidents': 'No incidents reported.',
      'refresh': 'Refresh',
      'back': 'Back',
      'notifications': 'Notifications',
      'noUnreadNotifications': 'No unread notifications.',
      'close': 'Close',
      'changeSchool': 'Change school',
      'parentSpace': 'Parent Portal',
      'noPublishedGrades': 'No grades published.',
      'noRecordedAbsences': 'No absences recorded.',
      'noAnnouncedEvents': 'No events announced.',
      'noChildPayments': 'No payments recorded for this child.',
      'officialFees': 'Official fees',
      'viewReportPdf': 'View / download report card PDF',
      'adminOnlyPage': 'This page is reserved for school administrators.',
      'examClassDescription':
          'View students whose files and fees are complete or incomplete.',
      'noExamClasses': 'No exam class has been configured.',
      'noStudentsInClass': 'No student enrolled in this class.',
      'upToDate': 'UP TO DATE',
      'notUpToDate': 'NOT UP TO DATE',
      'configurationSaved': 'Configuration saved',
      'feesPaid': 'Fees paid',
      'examClassSettings': 'Exam class settings',
      'completeStudents': 'Complete students',
      'enrolledStudents': 'Enrolled students',
      'saveExamConfigFirst':
          'Save the exam configuration first to display students.',
      'noEnrolledStudents': 'No student is enrolled in this class yet.',
      'examSettings': 'Exam settings',
      'requiredDocuments': 'Required documents',
      'required': 'Required',
      'optional': 'Optional',
      'examName': 'Exam name',
      'officialFeesFcfa': 'Official fees (FCFA)',
      'addDocument': 'Add a document',
      'addToProgram': 'Add to program',
      'mainChapter': 'Main chapter *',
      'chapterExample': 'E.g. Functions',
      'subChapterOptional': 'Subchapter (optional)',
      'loadProgramError': 'Unable to load program:',
      'saveImpossible': 'Unable to save:',
      'updateImpossible': 'Unable to update:',
      'noChapters': 'No chapters available.',
      'evaluationsExams': 'Assessments / Exams',
      'absencesSanctions': 'Absences / Sanctions',
      'teachingStaff': 'Teaching Staff',
      'financialManagement': 'Financial Management',
      'courseManagement': 'Course management',
      'gradeManagement': 'Grade management',
      'paymentManagement': 'Payment management',
      'founderVision': 'Strategic Vision ? Founder',
      'leadershipSupervision': 'Supervision and Leadership ? Management',
      'academicMonitoring': 'Academic Monitoring ? Censor',
      'schoolLifeDiscipline': 'School Life and Discipline ? General Supervisor',
      'teacherSpace': 'Teacher Portal',
      'saveErrorPrefix': 'Save error:',
      'notProvided': 'Not provided',
      'closeAndSaveYear': 'Close & save the year',
      'confirmClosure': 'Confirm closure',
      'academicYearLabel': 'Academic year label (e.g. 2025-2026)',
      'searchArchivedSchools':
          'Search by year (e.g. 2023-2024) or school name...',
      'closedSchoolYears': 'Closed school years',
      'refreshArchives': 'Refresh archives',
      'archivedCollections': 'Total archived collections',
      'cumulativeRevenue': 'Cumulative revenue',
      'incurredExpenses': 'Incurred expenses',
      'historicalNetBalance': 'Historical net balance',
      'cumulativeEnrollments': 'Cumulative enrollments',
      'lessonsTaught': 'Lessons taught',
      'consolidatedProfit': 'Consolidated overall profit',
      'finalNetBalance': 'Final net balance',
      'realizedRevenue': 'Realized revenue',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['fr']![key] ??
        key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['fr', 'en'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

extension AppLocalizationContext on BuildContext {
  String tr(String key) => AppLocalizations.of(this).translate(key);
}
