// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEU9psYsw3ICmtDoEp8QRr9dORulXFiLU',
    appId: '1:68400529263:web:f9d7bfd41fa5304b1e729a',
    messagingSenderId: '68400529263',
    projectId: 'edugest-fe40d',
    authDomain: 'edugest-fe40d.firebaseapp.com',
    storageBucket: 'edugest-fe40d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv0Duz0MSr3LO2ESt1IZK-fTKDMXdpacQ',
    appId: '1:68400529263:android:cd4e1899086dce2e1e729a',
    messagingSenderId: '68400529263',
    projectId: 'edugest-fe40d',
    storageBucket: 'edugest-fe40d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxUpsi16FQpSD6_LXiPaFtAUC4Uc9EXoA',
    appId: '1:68400529263:ios:29db03755ec11d611e729a',
    messagingSenderId: '68400529263',
    projectId: 'edugest-fe40d',
    storageBucket: 'edugest-fe40d.firebasestorage.app',
    iosBundleId: 'com.example.edugest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxUpsi16FQpSD6_LXiPaFtAUC4Uc9EXoA',
    appId: '1:68400529263:ios:29db03755ec11d611e729a',
    messagingSenderId: '68400529263',
    projectId: 'edugest-fe40d',
    storageBucket: 'edugest-fe40d.firebasestorage.app',
    iosBundleId: 'com.example.edugest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEU9psYsw3ICmtDoEp8QRr9dORulXFiLU',
    appId: '1:68400529263:web:b28f1d25bba69f921e729a',
    messagingSenderId: '68400529263',
    projectId: 'edugest-fe40d',
    authDomain: 'edugest-fe40d.firebaseapp.com',
    storageBucket: 'edugest-fe40d.firebasestorage.app',
  );
}
